main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

api_url = [
    path('v1/', include('api_v1.urls')),
    path('v2/', include('api_v2.urls'))
]

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('webapp.urls')),
                  path('accounts/', include('accounts.urls')),
                  path('api/', include(api_url)),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webapp/urls.py
from django.urls import path
from webapp.views import IndexViews, ArticleCreateView, ArticleView, ArticleUpdateView, \
    ArticleDeleteView, ArticleCommentCreateView, CommentUpdateView, CommentDeleteView, TestView

app_name = 'webapp'

urlpatterns = [
    path('', IndexViews.as_view(), name='index'),
    path('test/', TestView.as_view(), name='test'),
    path('article/<int:pk>/', ArticleView.as_view(), name='article_view'),
    path('article/<int:pk>/comment/add/', ArticleCommentCreateView.as_view(), name='article_comment_add'),
    path('articles/add/', ArticleCreateView.as_view(), name='article_add'),
    path('article/<int:pk>/update', ArticleUpdateView.as_view(), name='article_update'),
    path('article/<int:pk>/delete', ArticleDeleteView.as_view(), name='article_delete'),
    path('comment/<int:pk>/update', CommentUpdateView.as_view(), name='comment_update'),
    path('comment/<int:pk>/delete', CommentDeleteView.as_view(), name='comment_delete'),
]

webapp/models.py
from django.db import models
from django.urls import reverse

from django.contrib.auth import get_user_model

from webapp.validate import at_least_8


class Tag(models.Model):
    name = models.CharField(max_length=30, verbose_name='Тег')

    def __str__(self):
        return self.name


class Article(models.Model):
    title = models.CharField(max_length=50, null=False, blank=False, verbose_name="Заголовок")
    content = models.TextField(max_length=3000, null=False, blank=False, verbose_name="Контент",
                               validators=(at_least_8,))
    author = models.ForeignKey(get_user_model(), on_delete=models.SET_DEFAULT, default=1, related_name='articles',
                               verbose_name="Автор")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Время создания")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Время изменения")
    tags = models.ManyToManyField('webapp.Tag', related_name='articles', blank=True)

    class Meta:
        permissions = [
            ('сan_have_piece_of_pizza', 'Может съесть кусочек пиццы'),
        ]

    def get_absolute_url(self):
        return reverse('webapp:article_view', kwargs={'pk': self.pk})

    def get_comments_count(self):
        return self.comments.count()

    def __str__(self):
        return f'{self.pk}. {self.title}'


class Comment(models.Model):
    text = models.TextField(max_length=400, verbose_name='Комментарий')
    article = models.ForeignKey('webapp.Article', on_delete=models.CASCADE, related_name='comments',
                                verbose_name="Статья")
    author = models.ForeignKey(get_user_model(), on_delete=models.SET_DEFAULT, default=1, related_name='comments',
                               verbose_name="Автор")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Время создания")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Время изменения")

    def __str__(self):
        return f'{self.pk}. {self.text[:20]}'

webapp/forms.py
from django import forms
from django.forms import widgets, ValidationError
from webapp.models import Article, Comment


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['title', 'content', 'tags']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'content': forms.Textarea(attrs={'class': 'form-control'}),
            'tags': widgets.CheckboxSelectMultiple,
        }
        error_messages = {
            'content': {
                'required': 'Поле должно быть заполнено'
            }
        }

    def clean_title(self):
        title = self.cleaned_data['title']
        if len(title) < 5:
            self.add_error('title', ValidationError('Длина зтого поля должна составлять не меенее %(length)d символов!',
                                                    code='too_short', params={'length': 5}))
        return title

    def clean(self):
        cleaned_data = super().clean()
        if cleaned_data['title'] == cleaned_data.get('content', ''):
            raise ValidationError('Текст статьи не должен дублировать ее название!')
        return cleaned_data


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']


class ArticleDeleteForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['title']

    def clean_title(self):
        title = self.cleaned_data['title']
        if self.instance.title != title:
            raise ValidationError('Названия не совпадают')
        return title


class SimpleSearchForm(forms.Form):
    search = forms.CharField(max_length=50, required=False, label='Найти',
                             widget=widgets.TextInput(attrs={'class': "form-control w-25"}))

webapp/views/article_views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.db.models import Q
from django.urls import reverse_lazy
from django.utils.http import urlencode
from webapp.models import Article
from webapp.forms import ArticleForm, SimpleSearchForm, ArticleDeleteForm
from django.http import JsonResponse

from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, View


class TestView(View):
    def get(self, request, *args, **kwargs):
        # response = JsonResponse({'test': 2, 'test2': [1,2,3]})
        response = JsonResponse({'error': 'qweqweqweqwwe'})
        response.status_code =400

        return response


class IndexViews(ListView):
    template_name = 'article/index.html'
    context_object_name = 'articles'
    model = Article
    ordering = ('-created_at',)
    paginate_by = 3
    paginate_orphans = 2

    def get(self, request, *args, **kwargs):
        self.form = self.get_search_form()
        self.search_value = self.get_search_value()
        return super().get(request, *args, **kwargs)

    def get_search_form(self):
        return SimpleSearchForm(self.request.GET)

    def get_search_value(self):
        if self.form.is_valid():
            return self.form.cleaned_data['search']

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.search_value:
            queryset = queryset.filter(Q(title__icontains=self.search_value))
        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['form'] = self.form
        if self.search_value:
            context['query'] = urlencode({'search': self.search_value})
            context['search'] = self.search_value
        return context


class ArticleView(DetailView):
    template_name = 'article/article_view.html'
    model = Article

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        article = self.object
        comments = article.comments.order_by('-created_at')
        context['comments'] = comments
        return context



class ArticleCreateView(LoginRequiredMixin, CreateView):
    template_name = "article/article_create.html"
    model = Article
    form_class = ArticleForm

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)



class ArticleUpdateView(PermissionRequiredMixin, UpdateView):
    template_name = "article/article_update.html"
    form_class = ArticleForm
    model = Article
    context_object_name = 'article'
    permission_required = 'webapp.change_article'

    def has_permission(self):
        return super().has_permission() or self.get_object().author == self.request.user


class ArticleDeleteView(PermissionRequiredMixin, DeleteView):
    template_name = 'article/article_delete.html'
    model = Article
    context_object_name = 'article'
    success_url = reverse_lazy('webapp:index')
    form_class = ArticleDeleteForm
    permission_required = 'webapp.delete_article'

    def has_permission(self):
        return super().has_permission() or self.get_object().author == self.request.user

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.form_class(instance=self.object, data=request.POST)
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

webapp/views/base_views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import View, TemplateView


class CreateView(View):
    form_class = None
    template_name = None
    model = None
    redirect_url = None

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        context = {'form': form}
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        form = self.form_class(data=request.POST)
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        self.object = form.save()
        return redirect(self.get_redirect_url())

    def form_invalid(self, form):
        context = {'form': form}
        return render(self.request, self.template_name, context)

    def get_redirect_url(self):
        return self.redirect_url


class DeleteView(View):
    template_name = None
    confirm_deletion = True
    model = None
    key_kwarg = 'pk'
    context_key = 'object'
    redirect_url = ''

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.confirm_deletion:
            return render(request, self.template_name, self.get_context_data())
        else:
            self.perform_delete()
            return redirect(self.get_redirect_url())

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.perform_delete()
        return redirect(self.get_redirect_url())

    def perform_delete(self):
        self.object.delete()

    def get_context_data(self, **kwargs):
        return {self.context_key: self.object}

    def get_object(self):
        pk = self.kwargs.get(self.key_kwarg)
        return get_object_or_404(self.model, pk=pk)

    def get_redirect_url(self):
        return self.redirect_url


class UpdateView(View):
    form_class = None
    template_name = None
    redirect_url = ''
    model = None
    key_kwarg = 'pk'
    context_key = 'object'

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.form_class(instance=self.object)
        context = self.get_context_data(form=form)
        return render(request, self.template_name, context=context)

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.form_class(instance=self.object, data=request.POST)
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        self.object = form.save()
        return redirect(self.get_redirect_url())

    def form_invalid(self, form):
        context = self.get_context_data(form=form)
        return render(self.request, self.template_name, context=context)

    def get_object(self):
        pk = self.kwargs.get(self.key_kwarg)
        return get_object_or_404(self.model, pk=pk)

    def get_context_data(self, **my_kwargs):
        context = self.kwargs.copy()
        context[self.context_key] = self.object
        context.update(my_kwargs)
        return context

    def get_redirect_url(self):
        return self.redirect_url


class DetailView(TemplateView):
    context_key = 'object'
    model = None
    key_kwarg = 'pk'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context[self.context_key] = self.get_object()
        return context

    def get_object(self):
        pk = self.kwargs.get(self.key_kwarg)
        return get_object_or_404(self.model, pk=pk)


class ListView(TemplateView):
    model = None
    context_key = 'objects'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context[self.context_key] = self.get_objects()
        return context

    def get_objects(self):
        return self.model.objects.all()


class FormView(View):
    template_name = None
    form_class = None
    redirect_url = ''

    def get_context_data(self, **kwargs):
        return kwargs

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        context = self.get_context_data(form=form)
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        form = self.form_class(data=request.POST)
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def get_redirect_url(self):
        return self.redirect_url

    def form_valid(self, form):
        return redirect(self.get_redirect_url())

    def form_invalid(self, form):
        context = self.get_context_data(form=form)
        return render(self.request, self.template_name, context)

webapp/views/comment_views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse
from django.views.generic import CreateView, UpdateView, DeleteView

from webapp.forms import CommentForm
from webapp.models import Comment, Article


class ArticleCommentCreateView(LoginRequiredMixin, CreateView):
    template_name = 'comment/create.html'
    model = Comment
    form_class = CommentForm

    def get_success_url(self):
        return reverse('webapp:article_view', kwargs={'pk': self.object.article.pk})

    def form_valid(self, form):
        article = get_object_or_404(Article, pk=self.kwargs.get('pk'))
        form.instance.article = article
        form.instance.author = self.request.user
        return super().form_valid(form)


class CommentUpdateView(PermissionRequiredMixin, UpdateView):
    model = Comment
    template_name = 'comment/update.html'
    form_class = CommentForm
    context_object_name = 'comment'

    def has_permission(self):
        return self.request.user.has_perm('webapp.change_comment') or self.get_object().author == self.request.user

    def get_success_url(self):
        return reverse('webapp:article_view', kwargs={'pk': self.object.article.pk})

class CommentDeleteView(UserPassesTestMixin, DeleteView):
    model = Comment

    def test_func(self):
        return self.request.user.has_perm('webapp.delete_comment') or self.get_object().author == self.request.user

    def get(self, request, *args, **kwargs):
        return self.delete(request, *args, **kwargs)

    def get_success_url(self):
        return reverse('webapp:article_view', kwargs={'pk': self.object.article.pk })

webapp/templates/article/article_create.html
{% extends 'base.html' %}
{% block content %}
    <h1>Create Article</h1>

    <form action="" method="post">
        {% include 'partial/form.html' with button_text="Create" %}

    </form>
{% endblock %}

webapp/templates/article/article_delete.html
{% extends "base.html" %}
{% block title %}Delete Article{% endblock %}
{% block nav %}
    <li class="nav-item">
        <a class="nav-link" href="{% url 'webapp:article_view' article.pk %}">View</a>
    </li>
{% endblock %}
{% block content %}
    <h1>Are you sure want to delete article "{{ article.title }}"?</h1>
    <form method="POST" action="{% url "webapp:article_delete" article.pk %}" class="text-center">
        {% include 'partial/form.html' with button_text="Delete" %}
        <p><a href="{% url "webapp:article_view" article.pk %}">Next</a></p>
    </form>
{% endblock %}

webapp/templates/article/article_update.html
{% extends 'base.html' %}
{% block content %}
    <h1>Update Article</h1>

    <form action="" method="post">
        {% include 'partial/form.html' with button_text="Update" %}
    </form>
{% endblock %}

webapp/templates/article/article_view.html
{% extends 'base.html' %}

{% block nav %}

    {% if request.user.is_authenticated %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'webapp:article_add' %}">Add Article</a>
        </li>

        {% if perms.webapp.change_article or article.author == request.user %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'webapp:article_update' article.pk %}">Update</a>
            </li>
        {% endif %}
        {% if perms.webapp.delete_article  or article.author == request.user %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'webapp:article_delete' article.pk %}">Delete</a>
            </li>
        {% endif %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'webapp:article_comment_add' article.pk %}">Add Comment</a>
        </li>
    {% endif %}
{% endblock %}

{% block content %}

    <div class="card my-3">
        <div class="card-body">
            <h3 class="card-title fs-2">{{ article.title }}</h3>
            <p class="card-text text-secondary">Автор: {{ article.author }}</p>
            <p class="card-text text-secondary">Теги: {% for tag in article.tags.all %}
                {{ tag.name }} {% if  not forloop.last %},{% endif %}
            {% endfor %}</p>
            <p class="card-text">{{ article.content }}</p>
        </div>
    </div>
    <h3 class="ms-3">Comments:</h3>
    <div class="row">
        {% for comment in comments %}

            <div class="col-sm-4">
                <div class="card text-bg-light mb-3">
                    <div class="card-body">
                        <p class="card-text">{{ comment.text }}</p>

                        <div class="d-flex justify-content-around">
                            {% if perms.webapp.change_comment or comment.author == request.user %}
                                <a href="{% url 'webapp:comment_update' comment.pk %}"
                                   class="btn btn-success px-5">Update</a>
                            {% endif %}
                            {% if perms.webapp.delete_comment or comment.author == request.user %}
                                <a href="{% url 'webapp:comment_delete' comment.pk %}"
                                   class="btn btn-danger px-5">Delete</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        {% empty %}
            <p>Комментариев нет</p>
        {% endfor %}
    </div>
{% endblock %}

webapp/templates/article/index.html
{% extends 'base.html' %}


{% block nav %}
    {% if request.user.is_authenticated %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'webapp:article_add' %}">Add Article</a>
        </li>
    {% endif %}
{% endblock %}

{% block content %}
    {% include 'partial/simple_search.html' %}
    {% include 'partial/article_list_partial.html' %}

{% endblock %}